from mava.project.systems.online.independent_qrdqn.training import IndependentQRDQNTrainer
from mava.project.systems.online.independent_qrdqn.executing import IndependentQRDQNExecutor
from mava.project.systems.online.independent_qrdqn.system_builder import IndependentQRDQN